version: '3'

services:
    php:
        build: .docker
        container_name: symfony-environment
        ports:
            - "80:8000"
        volumes:
            - .:/var/www/symfony:delegated
        extra_hosts:
            - "docker.host:127.0.0.1"